server/tools.json
Yeti defaults: Remove license URL to avoid issues with existing studio envs
=> Yeti defaults: Remove license URL to avoid issues with existing studio envs

server/applications.json
The Blender 4.2 LTS version has been released: https://www.blender.org/download/
So this updates the default settings to include it.
1. Test whether Blender 4.2 works as intended
=> Add Blender 4.2 LTS to defaults

server/applications.json
Change `AVALON_HARMONY_WORKFILES_ON_LAUNCH` -> `AYON_HARMONY_WORKFILES_ON_LAUNCH`
See:
- https://github.com/ynput/ayon-harmony/blob/5a93fb2993d068cf2bfc95438c5eab55e4eba35b/client/ayon_harmony/api/lib.py#L201
- https://discord.com/channels/517362899170230292/563751989075378201/1267948379720257718
1. Defaults should be updated
2. Defaults should make sense with latest release of harmony.
=> Harmony: Update env var to the new key name in recent ayon-harmony

client/ayon_applications/addon.py
Don't use addon version when supplying statics on localhost.
To be able to use the uri one has to know which addon version is used, which is not really necessary for localhost, which has to run in tray, which can use only one version of an addon at a time.
=> Icons statics: Don't use version in local webserver path

client/ayon_applications/utils.py
Method `modify_application_launch_arguments` is optional on addon. It should not be defined on B
The base addon class is defined in ayon-core which should not provide applications specific definition of the method.
Nothing really changes now. This PR makes the method optional, so future version of ayon-core can remove it from base addon class.
=> Chore: Addon method to modify envrionments is optional

client/ayon_applications/utils.py
It can sometimes be hard to 'debug' why certain tool configurations may or may not work - or even recognize whether the tools are even applied to your current environment or not. This change makes this log message appear in console by default when launching an application.
I feel, especially with the change to new tools filtering with applications 1.0.0 having this available in logs will be helpful to debug.
1. Launch an app with applications.
2. Log should be visible in ayon console (where it previously wasn't by default).
=> Set applications "tools" being used as info log instead of debug

server/applications.json
Removed old variants and added more recent releases.
1. Validate added variants.
2. Make sure the defaults are actually working.
=> Chore: Update Application variants in default settings

server/applications.json, server/settings.py
Don't require `label` filled on application and tool variant.
Also removed labels that are same as name.
1. Create package, upload to server and add to your bundle.
2. Go to settings, remove application or tool variant label and save settings.
3. Both applications and tools selection combobox should use variant name as variant label.
Resolves https://github.com/ynput/ayon-applications/issues/28
=> Use variant name if label is not filled

server/actions.py
Disabled applications are not shown in webactions.
When profile specified that all applications should be visible based on profile filters, it showed even disabled applications.
1. Create package, upload it to AYON and add it to bundle.
2. Create profile in applications profiles to show all applications.
3. Only enabled applications should be shown on selected task.
Resolves https://github.com/ynput/ayon-applications/issues/26
=> Webactions: Skip disabled applications

server/tools.json
Example VRay Maya tool have invalid hosts filter.
There was invalid filter for hosts with `""` in host names filter.
1. Validate changes.
=> Default settings: VRay Maya has maya host

client/ayon_applications/utils.py
Log opening of last workfile was disabled only if `start_last_workfile is False` explicitly
Do not log this message if the last workfile was actually to be opened.
1. Start e.g. Blender with last workfile enabled.
2. The `Opening of last workfile was disabled by user` should not appear in the logs.
=> Log opening of last workfile was disabled only if `start_last_workfile is False` explicitly

client/ayon_applications/plugins/publish/collect_farm_env_variables.py
Fill environment variables for farm in publish plugins.
Move control to collect applications environment variables, needed for farm jobs, to applications addon.
1. At this moment probably nothing changed because deadline has to stop auto-fill the key.
Resolves https://github.com/ynput/ayon-applications/issues/41
=> Fill environment variables for farm jobs

server/applications.json
Remove 3dsmax addon directory environment as default setting regarding to https://github.com/ynput/ayon-3dsmax/pull/34
n/
1. Build and install application addon alongside the Max addon built with https://github.com/ynput/ayon-3dsmax/pull/34
2. Launch Max
3. AYON plugins should be installed and working successfully.
=> Remove 3dsmax addon directory enviroment

server/applications.json
Add Blender 4.4 to defaults
Include `AYON_BLENDER_USE_SYSTEM_PATH` in variant environment, for more details see: https://github.com/ynput/ayon-blender/pull/103
Requires `ayon-blender 0.2.10`
1. Launching Blender 4.4 should work with these defaults
=> Add Blender 4.4 to defaults

client/ayon_applications/utils.py
Use `merge_env_variables` and `compute_env_variables_structure` from ayon-core repository if are available.
The fallbacks should be removed after some time, which will require bump compatible version of ayon-core.
1. Test with latest ayon-core.
2. Make sure your task is using tools that have env variables to resolve.
3. The environments of application and tools should be resolved as before.
=> Chore: Use env tools functions from ayon core

server/applications.json
Add Autodesk Maya 2026 to defaults
Maya 2026 should be seen among other Maya versions.
=> Add Autodesk Maya 2026

server/applications.json
Add Fusion 19 and 20 to defaults
Note that Fusion 20 is currently in public beta still.
Also, Fusion 20 requires[ this fix in `ayon-fusion`](https://github.com/ynput/ayon-fusion/pull/41).
1. Fusion 19 and 20 should work with the new defaults
=> Add Fusion 19 and 20 to defaults

server/actions.py
Use project based settings for applications webactions.
1. Applications list in project settings are respected in webactions.
Resolves https://github.com/ynput/ayon-applications/issues/55
=> Webactions: Use project settings for applications list

client/ayon_applications/plugins/launcher_actions/debug_terminal.py
Fix check of icon filepath value.
Make sure `None` is not passed into `os.path.exists`.
1. Add custom application in studio settings.
2. Add the application to applications list (or use `All applications).
3. Debug terminal does not cause crashes when launched.
Resolves https://github.com/ynput/ayon-applications/issues/65
=> Debug terminal: Add check for icon value

server/actions.py
Webactions are using group labels.
The changes are backwards compatible so it works with AYON server below and above 1.8.0 .
This change is important for https://github.com/ynput/ayon-core/pull/1226 .
EDITED: This PR would break Web UI actions before this PR https://github.com/ynput/ayon-frontend/pull/1162  which is not yet in any release.
- For now nothing should change.
- When used with https://github.com/ynput/ayon-core/pull/1226 the application actions in launcher tool are grouped by DCC.
=> Webactions: Add group labels

server/__init__.py
Use new `get_launcher_response` on executor instead of `get_launcher_action_response`.
1. Webactions still do work with AYON server lower than 1.8.3 and newer than 1.8.3 .
=> Webaction: Use new executor function to run launcher action

client/ayon_applications/addon.py
Fix typehint of `launch_application` method.
The literal is expected in cli methods.
=> Chore: Fix typehint

server/actions.py
Change order of applications webaction to `0`.
1. Webactions are sorted earlier with https://github.com/ynput/ayon-core/pull/1226 .
=> Chore: Change order of actions to to '0'

server/settings.py
Add Environment field JSON validation in more places to avoid invalid JSON values being saved by an admin
This already existed in most places, but lacked in some - which still allowed you to break the settings for launching an application.
1. Try any of the "Environment" attributes in Applications addon, and set up invalid JSON values. It should be disallowed to save invalid values.
=> Add 'Environment' JSON validation to settings

server/settings.py
Refactor `conditionalEnum` -> `conditional_enum`
Avoid logs like:
```
DEBUG settings.settings_field | Deprecated argument: conditionalEnum
```
1. Check whether settings are still ok
=> Settings: Refactor `conditionalEnum` -> `conditional_enum`

client/ayon_applications/utils.py
Store used tools into `AYON_APP_TOOLS` environment variable.
The tool names are joined with a `;`. It is stored for information purposes to be stored to workfile entities (for example).
1. Launching of application will set up `AYON_APP_TOOLS` with used tools.
=> Environemnts: Store app tools to env variable on launch
